### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by MoonLGH** [ohsyme/skrep#2]
https://github.com/ohsyme/skrep/blob/8d1a7d06b747c6d956bda69b7270fedb8c081761/src/scraper/nsfw/hentaibatch.js#LL78C19-L78C26

pertama tama wtf is `Credits : Credits`
kedua lu define Credits dimane

**Comment by rraahh133** [comment]
> https://github.com/ohsyme/skrep/blob/8d1a7d06b747c6d956bda69b7270fedb8c081761/src/scraper/nsfw/hentaibatch.js#LL78C19-L78C26
> 
> pertama tama wtf is `Credits : Credits` kedua lu define Credits dimane

Buka settings.js mas 
2. Itu buat wm sebenernya

**Comment by MoonLGH** [comment]
bro could have just `Credits` not `Credits:Credits`

**Comment by rraahh133** [comment]
> bro could have just `Credits` not `Credits:Credits`

Iknow it tbh i just.copy paste before
